/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Ambulatorio(props) {
  const { nodes, materials } = useGLTF("/ambulatorio_e_boschDigital.glb");
  return (
    <group {...props} dispose={null} position={[-11,-3,-11]} >
      <group
        position={[10.82, 0.57, 10.1]}
        rotation={[-Math.PI / 2, 0, 0.02]}
        scale={0.02}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CA_401001.geometry}
          material={materials.Material}
          position={[-3.45, -1.52, -21.87]}
          rotation={[0, 0, -3.11]}
          scale={[1, 1.33, 0.47]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CA_402.geometry}
          material={materials["Retro Vibe 35"]}
          position={[3.46, 1.88, 16.16]}
          rotation={[0, 0, -3.11]}
          scale={[0.57, 0.77, 0.27]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CA_404.geometry}
          material={materials["Retro Vibe 37"]}
          position={[3.7, -6.43, 14.68]}
          rotation={[0, 0, -3.11]}
          scale={[0.35, 0.52, 0.01]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["chapeuzinho-1"].geometry}
          material={materials["Retro Vibe 36"]}
          position={[3.46, 1.88, 0.79]}
          rotation={[0, 0, -3.11]}
          scale={[0.47, 0.62, 0.22]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials["Material.001"]}
          position={[10.89, 1.79, 18.31]}
          rotation={[-Math.PI / 2, -0.06, -Math.PI / 2]}
          scale={[1000, 2790.53, 1340.86]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials["Material.001"]}
          position={[2.81, 6.18, 18.31]}
          rotation={[Math.PI / 2, -1.52, Math.PI / 2]}
          scale={[1000, 2790.53, 1340.86]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials["Material.001"]}
          position={[-4.04, 1.32, 18.31]}
          rotation={[Math.PI / 2, 0.07, Math.PI / 2]}
          scale={[1000, 2790.53, 1340.86]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials["Material.001"]}
          position={[4.21, -4.3, 18.31]}
          rotation={[-Math.PI / 2, 1.53, -Math.PI / 2]}
          scale={[1000, 2793.56, 1679.14]}
        />
      </group>
      <group
        position={[15.49, 1.3, 9.54]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder034.geometry}
          material={materials["None.049"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder034_1.geometry}
          material={materials["Material.051"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pin001.geometry}
        material={materials["Material.054"]}
        position={[16.88, 1.28, 4]}
        rotation={[1.6, -0.02, -0.05]}
        scale={0.23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath001.geometry}
        material={materials["Material.061"]}
        position={[8.7, 0.12, -1.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Academia.geometry}
        material={materials["Retro Vibe 29"]}
        position={[6.14, 0.04, 10.14]}
        rotation={[-1.57, 0.01, 1.79]}
        scale={[0.02, 0.02, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_106.geometry}
        material={materials["Retro Vibe 25"]}
        position={[15.54, 0.04, 9.62]}
        rotation={[-1.56, -0.05, 0.02]}
        scale={[0.02, 0.02, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_126.geometry}
        material={materials["Retro Vibe 32"]}
        position={[13.97, 0.06, 2.29]}
        rotation={[-Math.PI / 2, 0, 0.02]}
        scale={[0.02, 0.02, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_140.geometry}
        material={materials["Retro Vibe 8"]}
        position={[15.95, 0.07, 2.96]}
        rotation={[-Math.PI / 2, 0, 0.25]}
        scale={[0.02, 0.02, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_147.geometry}
        material={materials["Retro Vibe 11"]}
        position={[14.85, 0.07, 1.66]}
        rotation={[-Math.PI / 2, 0, 0.25]}
        scale={[0.02, 0.02, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_148.geometry}
        material={materials["Retro Vibe 10"]}
        position={[15.77, 0.07, 1.42]}
        rotation={[-Math.PI / 2, 0, 0.25]}
        scale={[0.02, 0.02, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_149.geometry}
        material={materials["Retro Vibe 9"]}
        position={[15.75, 0.07, 2.15]}
        rotation={[-Math.PI / 2, 0, 0.25]}
        scale={[0.02, 0.02, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_150.geometry}
        material={materials["Retro Vibe 14"]}
        position={[16.66, 0.07, 7.81]}
        rotation={[-Math.PI / 2, 0, 0.25]}
        scale={[0.02, 0.02, 0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_151.geometry}
        material={materials["Retro Vibe 16"]}
        position={[17.72, 0.08, 7.54]}
        rotation={[-Math.PI / 2, 0, 0.25]}
        scale={[0.02, 0.02, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_160.geometry}
        material={materials["Retro Vibe 6"]}
        position={[16.12, 0.08, 5.78]}
        rotation={[-Math.PI / 2, 0, 0.25]}
        scale={[0.02, 0.02, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_165.geometry}
        material={materials["Retro Vibe 17"]}
        position={[14.12, 0.06, 2.71]}
        rotation={[-Math.PI / 2, 0, 0.02]}
        scale={[0.02, 0.02, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_170.geometry}
        material={materials["Material.027"]}
        position={[17.59, 0.08, 7.07]}
        rotation={[-Math.PI / 2, 0, 0.25]}
        scale={[0.02, 0.02, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_180.geometry}
        material={materials["Retro Vibe 15"]}
        position={[17.86, 0.06, 8.42]}
        rotation={[-1.56, -0.02, 0.02]}
        scale={[0.02, 0.02, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_183.geometry}
        material={materials["Retro Vibe 19"]}
        position={[17.49, 0.08, 9.13]}
        rotation={[-1.58, 0.02, -2.87]}
        scale={[0.02, 0.02, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_204.geometry}
        material={materials["Retro Vibe 23"]}
        position={[12.94, 0.06, 10.58]}
        rotation={[-Math.PI / 2, 0, -2.89]}
        scale={[0.02, 0.02, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_205.geometry}
        material={materials["Retro Vibe 22"]}
        position={[14.72, 0.07, 10.06]}
        rotation={[-Math.PI / 2, 0, -2.89]}
        scale={[0.02, 0.02, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_220.geometry}
        material={materials["Retro Vibe 21"]}
        position={[14.99, 0.07, 10.28]}
        rotation={[-Math.PI / 2, 0, -2.89]}
        scale={[0.02, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_300.geometry}
        material={materials["Material.060"]}
        position={[14.5, 0.06, 5.21]}
        rotation={[-Math.PI / 2, 0, 0.02]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_320.geometry}
        material={materials["Future Vision"]}
        position={[14.91, 0.06, 6.79]}
        rotation={[-Math.PI / 2, 0, 0.02]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_325.geometry}
        material={materials["Retro Vibe 4"]}
        position={[14.31, 0.06, 4.37]}
        rotation={[-Math.PI / 2, 0, 0.02]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_340.geometry}
        material={materials["Retro Vibe 33"]}
        position={[12.01, -0.04, 3.5]}
        rotation={[-1.63, 0.02, 0.02]}
        scale={[0.02, 0.02, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_350.geometry}
        material={materials["Retro Vibe 12"]}
        position={[10.81, 0.04, 4.08]}
        rotation={[-Math.PI / 2, 0, -1.33]}
        scale={[0.02, 0.02, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_360.geometry}
        material={materials["Material.059"]}
        position={[13.05, 0.07, 6.47]}
        rotation={[-Math.PI / 2, 0, 0.02]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_370.geometry}
        material={materials["Beyond the Pines 1"]}
        position={[11.29, 0.06, 7]}
        rotation={[-Math.PI / 2, 0, 0.02]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_560.geometry}
        material={materials["Retro Vibe 30"]}
        position={[4.22, 0.03, 9.77]}
        rotation={[-Math.PI / 2, 0, 0.22]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_600.geometry}
        material={materials["Retro Vibe 27"]}
        position={[6.44, 0.04, 8.85]}
        rotation={[-Math.PI / 2, 0, 1.8]}
        scale={[0.02, 0.03, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DigiHub.geometry}
        material={materials["Retro Vibe 31"]}
        position={[4.36, 0.03, 9.14]}
        rotation={[-Math.PI / 2, 0, 0.2]}
        scale={[0.02, 0.02, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.KINDERHAUS.geometry}
        material={materials["Retro Vibe 28"]}
        position={[5.83, 0.04, 10.24]}
        rotation={[-Math.PI / 2, 0, 1.8]}
        scale={[0.02, 0.02, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Portaria_3001.geometry}
        material={materials["Retro Vibe 34"]}
        position={[9.64, 0.06, 11.36]}
        rotation={[-Math.PI / 2, 0, -2.97]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Portaria_4001.geometry}
        material={materials["Retro Vibe 18"]}
        position={[16.45, 0.08, 8.71]}
        rotation={[-Math.PI / 2, 0, -2.84]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Portaria_5001.geometry}
        material={materials["Retro Vibe 20"]}
        position={[15.89, 0.07, 9.03]}
        rotation={[-Math.PI / 2, 0, -2.84]}
        scale={[0.02, 0.02, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Portaria_8001.geometry}
        material={materials["Retro Vibe 13"]}
        position={[13.07, 0.06, 2.06]}
        rotation={[-Math.PI / 2, 0, 0.31]}
        scale={[0.02, 0.02, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Refeitorio.geometry}
        material={materials["Retro Vibe 24"]}
        position={[13.56, 0.07, 9.79]}
        rotation={[-Math.PI / 2, 0, -2.89]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.elevador_401.geometry}
        material={materials["Material.062"]}
        position={[10.31, 0.37, 10.33]}
        rotation={[0, -0.7, 0]}
        scale={[18.45, 25.44, 18.45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Portaria_1001.geometry}
        material={materials["Retro Vibe 18.002"]}
        position={[12.98, 0.08, 12.14]}
        rotation={[-Math.PI / 2, 0, -2.96]}
        scale={[0.03, 0.03, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Portaria_2001.geometry}
        material={nodes.Portaria_2001.material}
        position={[16.14, 0.15, 13]}
        rotation={[0.22, -1.55, 0.22]}
        scale={[1, 0.51, 1]}
      />
      <group
        position={[1.72, 0.04, 7.15]}
        rotation={[Math.PI, -0.36, Math.PI]}
        scale={[0.28, 0.09, 0.15]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={materials.White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={materials.Green}
        />
      </group>
      <group
        position={[2.74, 0.04, 6.54]}
        rotation={[-Math.PI, 1.23, -Math.PI]}
        scale={[0.13, 0.09, 0.07]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials.White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials.Green}
        />
      </group>
      <group
        position={[2.56, 0.04, 6.01]}
        rotation={[-Math.PI, 1.23, -Math.PI]}
        scale={[0.13, 0.09, 0.07]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003.geometry}
          material={materials.White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_1.geometry}
          material={materials.Green}
        />
      </group>
      <group
        position={[2.23, 0.05, 8.34]}
        rotation={[-Math.PI, 1.22, -Math.PI]}
        scale={[0.12, 0.09, 0.07]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004.geometry}
          material={materials.White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_1.geometry}
          material={materials.Green}
        />
      </group>
      <group
        position={[5.39, 0.04, 7.84]}
        rotation={[0, 0.24, 0]}
        scale={[0.16, 0.09, 0.09]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005.geometry}
          material={materials.White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_1.geometry}
          material={materials.Green}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pin002.geometry}
        material={materials["Material.056"]}
        position={[16.88, 1.28, 4]}
        rotation={[1.6, -0.02, -0.05]}
        scale={0.23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pin003.geometry}
        material={materials["Material.057"]}
        position={[16.88, 1.28, 4]}
        rotation={[1.6, -0.02, -0.05]}
        scale={0.23}
      />
      <group
        position={[2.9, 0.04, 8.75]}
        rotation={[0, -0.91, 0]}
        scale={[0.11, 0.01, 0.15]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_1.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_2.geometry}
          material={materials["Material.026"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_3.geometry}
          material={materials["Material.028"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_4.geometry}
          material={materials["Material.029"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_5.geometry}
          material={materials["Material.030"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_6.geometry}
          material={materials["Material.031"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_7.geometry}
          material={materials["Material.032"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_8.geometry}
          material={nodes.Cube035_8.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_9.geometry}
          material={materials["Material.034"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_10.geometry}
          material={materials["Material.035"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_11.geometry}
          material={materials["Material.036"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_12.geometry}
          material={materials["Material.037"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_13.geometry}
          material={materials["Material.038"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_14.geometry}
          material={materials["Material.039"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_15.geometry}
          material={materials["Material.040"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_16.geometry}
          material={materials["Material.041"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_17.geometry}
          material={materials["Material.042"]}
        />
      </group>
      <group
        position={[3.04, 0.04, 8.93]}
        rotation={[0, -0.91, 0]}
        scale={[0.11, 0.01, 0.15]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_1.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_2.geometry}
          material={materials["Material.026"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_3.geometry}
          material={materials["Material.028"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_4.geometry}
          material={materials["Material.029"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_5.geometry}
          material={materials["Material.030"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_6.geometry}
          material={materials["Material.031"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_7.geometry}
          material={materials["Material.032"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_8.geometry}
          material={nodes.Cube048_8.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_9.geometry}
          material={materials["Material.034"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_10.geometry}
          material={materials["Material.035"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_11.geometry}
          material={materials["Material.036"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_12.geometry}
          material={materials["Material.037"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_13.geometry}
          material={materials["Material.038"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_14.geometry}
          material={materials["Material.039"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_15.geometry}
          material={materials["Material.040"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_16.geometry}
          material={materials["Material.041"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_17.geometry}
          material={materials["Material.042"]}
        />
      </group>
      <group
        position={[2.81, 0.03, 7.66]}
        rotation={[0, 0.32, 0]}
        scale={[0.11, 0.01, 0.15]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_1.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_2.geometry}
          material={materials["Material.026"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_3.geometry}
          material={materials["Material.028"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_4.geometry}
          material={materials["Material.029"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_5.geometry}
          material={materials["Material.030"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_6.geometry}
          material={materials["Material.031"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_7.geometry}
          material={materials["Material.032"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_8.geometry}
          material={nodes.Cube061_8.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_9.geometry}
          material={materials["Material.034"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_10.geometry}
          material={materials["Material.035"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_11.geometry}
          material={materials["Material.036"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_12.geometry}
          material={materials["Material.037"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_13.geometry}
          material={materials["Material.038"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_14.geometry}
          material={materials["Material.039"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_15.geometry}
          material={materials["Material.040"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_16.geometry}
          material={materials["Material.041"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_17.geometry}
          material={materials["Material.042"]}
        />
      </group>
      <group
        position={[3.02, 0.04, 7.59]}
        rotation={[0, 0.32, 0]}
        scale={[0.11, 0.01, 0.15]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_1.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_2.geometry}
          material={materials["Material.026"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_3.geometry}
          material={materials["Material.028"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_4.geometry}
          material={materials["Material.029"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_5.geometry}
          material={materials["Material.030"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_6.geometry}
          material={materials["Material.031"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_7.geometry}
          material={materials["Material.032"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_8.geometry}
          material={nodes.Cube104_8.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_9.geometry}
          material={materials["Material.034"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_10.geometry}
          material={materials["Material.035"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_11.geometry}
          material={materials["Material.036"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_12.geometry}
          material={materials["Material.037"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_13.geometry}
          material={materials["Material.038"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_14.geometry}
          material={materials["Material.039"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_15.geometry}
          material={materials["Material.040"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_16.geometry}
          material={materials["Material.041"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_17.geometry}
          material={materials["Material.042"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mapa.geometry}
        material={materials["Material.003"]}
        position={[10.92, 0.03, 7.13]}
        rotation={[0.22, -1.55, 0.22]}
        scale={[0.96, 0.12, 1.02]}
      />
    </group>
  );
}

useGLTF.preload("/ambulatorio_e_boschDigital.glb");