/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import PlantaBtc from "../../pages/teste/telaBtc"
import Planta from "@/pages/planta";

var num = 1

export function Planta_cpin(props) {

  const { nodes, materials } = useGLTF("/planta_inteira.glb");
  return (
    <group {...props} dispose={null} position={[-11, -3, -11]} >
      <group
        position={[10.82, 0.57, 10.1]}
        rotation={[-Math.PI / 2, 0, 0.02]}
        scale={0.02}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CA_401001.geometry}
          onClick={()=>{props.select('Chapeuzinho')}}
          material={materials.Material}
          position={[-3.47, -2.82, -21.87]}
          rotation={[0, 0, -3.11]}
          scale={[1, 1.33, 0.47]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CA_402.geometry}
          material={materials["Retro Vibe 35"]}
          position={[3.46, 1.88, 16.16]}
          rotation={[0, 0, -3.11]}
          scale={[0.57, 0.77, 0.27]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CA_404.geometry}
          material={materials["Retro Vibe 37"]}
          position={[3.7, -6.43, 14.68]}
          rotation={[0, 0, -3.11]}
          scale={[0.35, 0.52, 0.01]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["chapeuzinho-1"].geometry}
          material={materials["Retro Vibe 36"]}
          position={[3.46, 1.88, 0.79]}
          rotation={[0, 0, -3.11]}
          scale={[0.47, 0.62, 0.22]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials["Material.001"]}
          position={[10.89, 1.79, 18.31]}
          rotation={[-Math.PI / 2, -0.06, -Math.PI / 2]}
          scale={[1000, 2790.53, 1340.86]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials["Material.001"]}
          position={[2.81, 6.18, 18.31]}
          rotation={[Math.PI / 2, -1.52, Math.PI / 2]}
          scale={[1000, 2790.53, 1340.86]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials["Material.001"]}
          position={[-4.04, 1.32, 18.31]}
          rotation={[Math.PI / 2, 0.07, Math.PI / 2]}
          scale={[1000, 2790.53, 1340.86]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials["Material.001"]}
          position={[4.21, -4.3, 18.31]}
          rotation={[-Math.PI / 2, 1.53, -Math.PI / 2]}
          scale={[1000, 2793.56, 1679.14]}
        />
      </group>
      <group
        position={[15.02, 1.3, 10.29]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          visible={props.pins}
          receiveShadow
          geometry={nodes.Cylinder026_1.geometry}
          material={materials["None.032"]}
        />
        <mesh
          castShadow
          visible={props.pins}
          receiveShadow
          geometry={nodes.Cylinder026_2.geometry}
          material={materials["Material.053"]}
        />
      </group>
      <group
        position={[15.51, 1.3, 9.6]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder034_1.geometry}
          material={materials["None.049"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder034_2.geometry}
          material={materials["Material.051"]}
        />
      </group>
      <group
        position={[14.03, 1.3, 2.68]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder035_1.geometry}
          material={materials["None.050"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder035_2.geometry}
          material={materials["Material.050"]}
        />
      </group>
      <group
        position={[15.96, 1.3, 2.94]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder036.geometry}
          material={materials["None.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder036_1.geometry}
          material={materials["Material.049"]}
        />
      </group>
      <group
        position={[15.78, 1.3, 1.43]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          visible={props.pins}
          receiveShadow
          geometry={nodes.Cylinder037.geometry}
          material={materials["None.031"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder037_1.geometry}
          material={materials["Material.047"]}
        />
      </group>
      <group
        position={[14.86, 1.3, 1.67]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder038.geometry}
          material={materials["None.033"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder038_1.geometry}
          material={materials["Material.048"]}
        />
      </group>
      <group
        position={[16.74, 1.3, 7.8]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder039.geometry}
          material={materials["None.054"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder039_1.geometry}
          material={materials["Material.045"]}
        />
      </group>
      <group
        position={[17.77, 1.3, 7.55]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder040.geometry}
          material={materials["None.055"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder040_1.geometry}
          material={materials["Material.044"]}
        />
      </group>
      <group
        position={[15.76, 1.3, 2.14]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder041.geometry}
          material={materials["None.056"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder041_1.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[17.48, 1.3, 9.15]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder043.geometry}
          material={materials["None.058"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder043_1.geometry}
          material={materials["Material.023"]}
        />
      </group>
      <group
        position={[17.9, 1.3, 8.38]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder044.geometry}
          material={materials["None.059"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder044_1.geometry}
          material={materials["Material.024"]}
        />
      </group>
      <group
        position={[14.02, 1.3, 4.3]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder045.geometry}
          material={materials["None.060"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder045_1.geometry}
          material={materials["Material.043"]}
        />
      </group>
      <group
        position={[13.61, 1.3, 9.83]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder046.geometry}
          material={materials["None.034"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder046_1.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <group
        position={[13.07, 1.3, 6.63]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder047.geometry}
          material={materials["None.035"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder047_1.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <group
        position={[11.19, 1.3, 7.17]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder048.geometry}
          material={materials["None.036"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder048_1.geometry}
          material={materials["Material.008"]}
        />
      </group>
      <group
        position={[12.94, 1.3, 10.6]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder049.geometry}
          material={materials["None.064"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder049_1.geometry}
          material={materials["Material.021"]}
        />
      </group>
      <group
        position={[14.8, 1.3, 6.39]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder050.geometry}
          material={materials["None.065"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder050_1.geometry}
          material={materials["Material.019"]}
        />
      </group>
      <group
        position={[15.04, 1.3, 7.22]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder051.geometry}
          material={materials["None.066"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder051_1.geometry}
          material={materials["Material.018"]}
        />
      </group>
      <group
        position={[14.73, 1.3, 10.06]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder052.geometry}
          material={materials["None.067"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder052_1.geometry}
          material={materials["Material.020"]}
        />
      </group>
      <group
        position={[10.78, 1.09, 4.11]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.14, 0.39, 0.13]}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Text052.geometry}
          material={materials["Material.015"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Text052_1.geometry}
          material={materials["None.068"]}
        />
      </group>
      <group
        position={[10.76, 2.39, 10.22]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder055.geometry}
          material={materials["None.070"]}
        />
        <mesh
          castShadow
          visible={props.pins}
          receiveShadow
          geometry={nodes.Cylinder055_1.geometry}
          material={materials["Material.014"]}
        />
      </group>
      <group
        position={[12.04, 1.3, 3.48]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder056.geometry}
          material={materials["None.071"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder056_1.geometry}
          material={materials["Material.016"]}
        />
      </group>
      <group
        position={[14.42, 1.3, 5.14]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder057.geometry}
          material={materials["None.072"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder057_1.geometry}
          material={materials["Material.017"]}
        />
      </group>
      <group
        position={[5.71, 1.3, 9.97]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder059.geometry}
          material={materials["None.074"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder059_1.geometry}
          material={materials["Material.009"]}
        />
      </group>
      <group
        position={[4.6, 1.3, 9.05]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder060.geometry}
          material={materials["None.075"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder060_1.geometry}
          material={materials["Material.013"]}
        />
      </group>
      <group
        position={[4.25, 1.3, 9.75]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder061.geometry}
          material={materials["None.076"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder061_1.geometry}
          material={materials["Material.012"]}
        />
      </group>
      <group
        position={[6.12, 1.3, 10.29]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder062.geometry}
          material={materials["None.077"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder062_1.geometry}
          material={materials["Material.011"]}
        />
      </group>
      <group
        position={[6.41, 1.3, 8.81]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder063.geometry}
          material={materials["None.078"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder063_1.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <group
        position={[17.19, 1.3, 5.6]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder065.geometry}
          material={materials["None.038"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder065_1.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group
        position={[16.13, 1.3, 5.65]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder066.geometry}
          material={materials["None.081"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder066_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pin001.geometry}
        material={materials["Material.054"]}
        position={[16.89, 2.35, 4.33]}
        rotation={[1.6, -0.02, -0.05]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Academia.geometry}
        material={materials["Retro Vibe 29"]}
        position={[6.14, 0.04, 10.14]}
        rotation={[-1.57, 0.01, 1.79]}
        scale={[0.02, 0.02, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_106.geometry}
        onClick={()=>{props.select('Bosch Digital')}}
        material={materials["Retro Vibe 25"]}
        position={[15.54, 0.04, 9.68]}
        rotation={[-1.56, -0.05, 0.02]}
        scale={[0.02, 0.02, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        onClick={() => { }}
        geometry={nodes.CA_126.geometry}
        material={materials["Retro Vibe 32"]}
        position={[13.97, 0.06, 2.29]}
        rotation={[-Math.PI / 2, 0, 0.02]}
        scale={[0.02, 0.02, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        onClick={() => { }}
        geometry={nodes.CA_140.geometry}
        material={materials["Retro Vibe 8"]}
        position={[15.95, 0.07, 2.96]}
        rotation={[-Math.PI / 2, 0, 0.25]}
        scale={[0.02, 0.02, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_147.geometry}
        onClick={() => { }}
        material={materials["Retro Vibe 11"]}
        position={[14.85, 0.07, 1.66]}
        rotation={[-Math.PI / 2, 0, 0.25]}
        scale={[0.02, 0.02, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_148.geometry}
        onClick={() => { }}
        material={materials["Retro Vibe 10"]}
        position={[15.77, 0.07, 1.42]}
        rotation={[-Math.PI / 2, 0, 0.25]}
        scale={[0.02, 0.02, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_149.geometry}
        onClick={() => { }}
        material={materials["Retro Vibe 9"]}
        position={[15.75, 0.07, 2.15]}
        rotation={[-Math.PI / 2, 0, 0.25]}
        scale={[0.02, 0.02, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        onClick={() => { }}
        geometry={nodes.CA_150.geometry}
        material={materials["Retro Vibe 14"]}
        position={[16.66, 0.07, 7.81]}
        rotation={[-Math.PI / 2, 0, 0.25]}
        scale={[0.02, 0.02, 0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_151.geometry}
        onClick={() => { }}
        material={materials["Retro Vibe 16"]}
        position={[17.72, 0.08, 7.54]}
        rotation={[-Math.PI / 2, 0, 0.25]}
        scale={[0.02, 0.02, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_160.geometry}
        onClick={() => { }}
        material={materials["Retro Vibe 6"]}
        position={[16.12, 0.08, 5.78]}
        rotation={[-Math.PI / 2, 0, 0.25]}
        scale={[0.02, 0.02, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_165.geometry}
        onClick={() => { }}
        material={materials["Retro Vibe 17"]}
        position={[14.12, 0.06, 2.71]}
        rotation={[-Math.PI / 2, 0, 0.02]}
        scale={[0.02, 0.02, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_170.geometry}
        onClick={() => { }}
        material={materials["Material.027"]}
        position={[17.59, 0.08, 7.07]}
        rotation={[-Math.PI / 2, 0, 0.25]}
        scale={[0.02, 0.02, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_180.geometry}
        onClick={() => { }}
        material={materials["Retro Vibe 15"]}
        position={[17.86, 0.06, 8.42]}
        rotation={[-1.56, -0.02, 0.02]}
        scale={[0.02, 0.02, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_183.geometry}
        material={materials["Retro Vibe 19"]}
        position={[17.45, 0.08, 9.13]}
        rotation={[-1.58, 0.02, -2.87]}
        scale={[0.02, 0.02, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_204.geometry}
        onClick={() => { }}
        material={materials["Retro Vibe 23"]}
        position={[12.94, 0.06, 10.6]}
        rotation={[-Math.PI / 2, 0, -2.89]}
        scale={[0.02, 0.02, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_205.geometry}
        onClick={() => { }}
        material={materials["Retro Vibe 22"]}
        position={[14.72, 0.07, 10.06]}
        rotation={[-Math.PI / 2, 0, -2.89]}
        scale={[0.02, 0.02, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_220.geometry}
        onClick={() => { }}
        material={materials["Retro Vibe 21"]}
        position={[14.99, 0.07, 10.28]}
        rotation={[-Math.PI / 2, 0, -2.89]}
        scale={[0.02, 0.03, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_300.geometry}
        onClick={() => { }}
        material={materials["Material.060"]}
        position={[14.5, 0.06, 5.21]}
        rotation={[-Math.PI / 2, 0, 0.02]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_320.geometry}
        onClick={() => { }}
        material={materials["Future Vision"]}
        position={[14.91, 0.06, 6.79]}
        rotation={[-Math.PI / 2, 0, 0.02]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_325.geometry}
        onClick={() => { }}
        material={materials["Retro Vibe 4"]}
        position={[14.31, 0.06, 4.37]}
        rotation={[-Math.PI / 2, 0, 0.02]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        onClick={() => { }}
        geometry={nodes.CA_340.geometry}
        material={materials["Retro Vibe 33"]}
        position={[12.01, -0.04, 3.5]}
        rotation={[-1.63, 0.02, 0.02]}
        scale={[0.02, 0.02, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_350.geometry}
        onClick={() => { }}
        material={materials["Retro Vibe 12"]}
        position={[10.81, 0.04, 4.08]}
        rotation={[-Math.PI / 2, 0, -1.33]}
        scale={[0.02, 0.02, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_360.geometry}
        onClick={() => { props.select('Eletrical Drives') }}
        material={materials["Material.059"]}
        position={[13.05, 0.07, 6.58]}
        rotation={[-Math.PI / 2, 0, 0.02]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_370.geometry}
        onClick={() => { props.select('Power Tools') }}
        material={materials["Beyond the Pines 1"]}
        position={[11.29, 0.06, 7.08]}
        rotation={[-Math.PI / 2, 0, 0.02]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_560.geometry}
        onClick={() => { }}
        material={materials["Retro Vibe 30"]}
        position={[4.22, 0.03, 9.77]}
        rotation={[-Math.PI / 2, 0, 0.22]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CA_600.geometry}
        onClick={() => { props.select('BTC') }}
        material={materials["Retro Vibe 27"]}
        position={[6.44, 0.04, 8.85]}
        rotation={[-Math.PI / 2, 0, 1.8]}
        scale={[0.02, 0.03, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DigiHub.geometry}
        onClick={() => { props.select('Digihub') }}
        material={materials["Retro Vibe 31"]}
        position={[4.36, 0.03, 9.14]}
        rotation={[-Math.PI / 2, 0, 0.2]}
        scale={[0.02, 0.02, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.KINDERHAUS.geometry}
        onClick={() => {}}
        material={materials["Retro Vibe 28"]}
        position={[5.83, 0.04, 10.24]}
        rotation={[-Math.PI / 2, 0, 1.8]}
        scale={[0.02, 0.02, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Portaria_3001.geometry}
        onClick={() => { }}
        material={materials["Retro Vibe 34"]}
        position={[9.64, 0.06, 11.36]}
        rotation={[-Math.PI / 2, 0, -2.97]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Portaria_4001.geometry}
        onClick={() => { }}
        material={materials["Retro Vibe 18"]}
        position={[16.45, 0.08, 8.71]}
        rotation={[-Math.PI / 2, 0, -2.84]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Portaria_5001.geometry}
        onClick={() => { }}
        material={materials["Retro Vibe 20"]}
        position={[15.89, 0.07, 9.03]}
        rotation={[-Math.PI / 2, 0, -2.84]}
        scale={[0.02, 0.02, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Portaria_8001.geometry}
        onClick={() => { }}
        material={materials["Retro Vibe 13"]}
        position={[13.07, 0.06, 2.06]}
        rotation={[-Math.PI / 2, 0, 0.31]}
        scale={[0.02, 0.02, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Refeitorio.geometry}
        onClick={() => { }}
        material={materials["Retro Vibe 24"]}
        position={[13.59, 0.07, 9.81]}
        rotation={[-Math.PI / 2, 0, -2.89]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.elevador_401.geometry}
        onClick={() => { }}
        material={materials["Material.062"]}
        position={[10.31, 0.37, 10.33]}
        rotation={[0, -0.7, 0]}
        scale={[18.45, 25.44, 18.45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Portaria_1001.geometry}
        onClick={() => { }}
        material={materials["Retro Vibe 18.002"]}
        position={[12.98, 0.08, 12.14]}
        rotation={[-Math.PI / 2, 0, -2.96]}
        scale={[0.03, 0.03, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Portaria_2001.geometry}
        onClick={() => { }}
        material={nodes.Portaria_2001.material}
        position={[16.14, 0.15, 13]}
        rotation={[0.22, -1.55, 0.22]}
        scale={[1, 0.51, 1]}
      />
      <group
        position={[1.72, 0.04, 7.15]}
        rotation={[Math.PI, -0.36, Math.PI]}
        scale={[0.28, 0.09, 0.15]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={materials.White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={materials.Green}
        />
      </group>
      <group
        position={[2.74, 0.04, 6.54]}
        rotation={[-Math.PI, 1.23, -Math.PI]}
        scale={[0.13, 0.09, 0.07]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials.White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials.Green}
        />
      </group>
      <group
        position={[2.56, 0.04, 6.01]}
        rotation={[-Math.PI, 1.23, -Math.PI]}
        scale={[0.13, 0.09, 0.07]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003.geometry}
          material={materials.White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_1.geometry}
          material={materials.Green}
        />
      </group>
      <group
        position={[2.23, 0.05, 8.34]}
        rotation={[-Math.PI, 1.22, -Math.PI]}
        scale={[0.12, 0.09, 0.07]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004.geometry}
          material={materials.White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_1.geometry}
          material={materials.Green}
        />
      </group>
      <group
        position={[5.39, 0.04, 7.84]}
        rotation={[0, 0.24, 0]}
        scale={[0.16, 0.09, 0.09]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005.geometry}
          material={materials.White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_1.geometry}
          material={materials.Green}
        />
      </group>
      <group
        position={[12.97, 1.2, 12.16]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.17, 0.25, 0.17]}
      >
        <mesh
          castShadow
          visible={props.pins}
          receiveShadow
          geometry={nodes.Cylinder002_1.geometry}
          material={materials["None.030"]}
        />
        <mesh
          castShadow
          visible={props.pins}
          receiveShadow
          geometry={nodes.Cylinder002_2.geometry}
          material={materials["Material.096"]}
        />
      </group>
      <group
        position={[16.12, 0.78, 12.94]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          visible={props.pins}
          receiveShadow
          geometry={nodes.Cylinder020.geometry}
          material={materials["None.079"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder020_1.geometry}
          material={materials["Material.052"]}
        />
      </group>
      <group
        position={[9.64, 1.22, 11.38]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          visible={props.pins}
          receiveShadow
          geometry={nodes.Cylinder017_1.geometry}
          material={materials["None.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder017_2.geometry}
          material={materials["Material.089"]}
        />
      </group>
      <group
        position={[16.43, 1.22, 8.71]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          visible={props.pins}
          receiveShadow
          geometry={nodes.Cylinder029.geometry}
          material={materials["None.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder029_1.geometry}
          material={materials["Material.085"]}
        />
      </group>
      <group
        position={[15.9, 1.18, 9.04]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder013_1.geometry}
          material={materials["None.018"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder013_2.geometry}
          material={materials["Material.055"]}
        />
      </group>
      <group
        position={[13.09, 1.2, 2.05]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.17, 0.25, 0.17]}
      >
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder001_1.geometry}
          material={materials["None.029"]}
        />
        <mesh
          castShadow
          receiveShadow
          visible={props.pins}
          geometry={nodes.Cylinder001_2.geometry}
          material={materials["Material.095"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pin002.geometry}
        material={materials["Material.056"]}
        position={[16.89, 2.35, 4.33]}
        rotation={[1.6, -0.02, -0.05]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pin003.geometry}
        material={materials["Material.057"]}
        position={[16.89, 2.35, 4.33]}
        rotation={[1.6, -0.02, -0.05]}
        scale={0.36}
      />
      <group
        position={[2.9, 0.04, 8.75]}
        rotation={[0, -0.91, 0]}
        scale={[0.11, 0.01, 0.15]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_1.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_2.geometry}
          material={materials["Material.026"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_3.geometry}
          material={materials["Material.028"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_4.geometry}
          material={materials["Material.029"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_5.geometry}
          material={materials["Material.030"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_6.geometry}
          material={materials["Material.031"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_7.geometry}
          material={materials["Material.032"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_8.geometry}
          material={nodes.Cube035_8.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_9.geometry}
          material={materials["Material.034"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_10.geometry}
          material={materials["Material.035"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_11.geometry}
          material={materials["Material.036"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_12.geometry}
          material={materials["Material.037"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_13.geometry}
          material={materials["Material.038"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_14.geometry}
          material={materials["Material.039"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_15.geometry}
          material={materials["Material.040"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_16.geometry}
          material={materials["Material.041"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_17.geometry}
          material={materials["Material.042"]}
        />
      </group>
      <group
        position={[3.04, 0.04, 8.93]}
        rotation={[0, -0.91, 0]}
        scale={[0.11, 0.01, 0.15]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_1.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_2.geometry}
          material={materials["Material.026"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_3.geometry}
          material={materials["Material.028"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_4.geometry}
          material={materials["Material.029"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_5.geometry}
          material={materials["Material.030"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_6.geometry}
          material={materials["Material.031"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_7.geometry}
          material={materials["Material.032"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_8.geometry}
          material={nodes.Cube048_8.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_9.geometry}
          material={materials["Material.034"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_10.geometry}
          material={materials["Material.035"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_11.geometry}
          material={materials["Material.036"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_12.geometry}
          material={materials["Material.037"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_13.geometry}
          material={materials["Material.038"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_14.geometry}
          material={materials["Material.039"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_15.geometry}
          material={materials["Material.040"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_16.geometry}
          material={materials["Material.041"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_17.geometry}
          material={materials["Material.042"]}
        />
      </group>
      <group
        position={[2.81, 0.03, 7.66]}
        rotation={[0, 0.32, 0]}
        scale={[0.11, 0.01, 0.15]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_1.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_2.geometry}
          material={materials["Material.026"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_3.geometry}
          material={materials["Material.028"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_4.geometry}
          material={materials["Material.029"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_5.geometry}
          material={materials["Material.030"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_6.geometry}
          material={materials["Material.031"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_7.geometry}
          material={materials["Material.032"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_8.geometry}
          material={nodes.Cube061_8.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_9.geometry}
          material={materials["Material.034"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_10.geometry}
          material={materials["Material.035"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_11.geometry}
          material={materials["Material.036"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_12.geometry}
          material={materials["Material.037"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_13.geometry}
          material={materials["Material.038"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_14.geometry}
          material={materials["Material.039"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_15.geometry}
          material={materials["Material.040"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_16.geometry}
          material={materials["Material.041"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube061_17.geometry}
          material={materials["Material.042"]}
        />
      </group>
      <group
        position={[3.02, 0.04, 7.59]}
        rotation={[0, 0.32, 0]}
        scale={[0.11, 0.01, 0.15]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_1.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_2.geometry}
          material={materials["Material.026"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_3.geometry}
          material={materials["Material.028"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_4.geometry}
          material={materials["Material.029"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_5.geometry}
          material={materials["Material.030"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_6.geometry}
          material={materials["Material.031"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_7.geometry}
          material={materials["Material.032"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_8.geometry}
          material={nodes.Cube104_8.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_9.geometry}
          material={materials["Material.034"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_10.geometry}
          material={materials["Material.035"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_11.geometry}
          material={materials["Material.036"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_12.geometry}
          material={materials["Material.037"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_13.geometry}
          material={materials["Material.038"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_14.geometry}
          material={materials["Material.039"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_15.geometry}
          material={materials["Material.040"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_16.geometry}
          material={materials["Material.041"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube104_17.geometry}
          material={materials["Material.042"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mapa.geometry}
        material={materials["Material.003"]}
        position={[10.92, 0.03, 7.13]}
        rotation={[0.22, -1.55, 0.22]}
        scale={[0.96, 0.12, 1.02]}
      />
    </group>
  );
}

useGLTF.preload("/planta_inteira.glb");
