import React, { useEffect, useState } from "react";
import Head from 'next/head'
import Navbar from "@/components/Navbar";
import Background from "@/components/Background";
import Acessibilidade from "@/components/Acessibilidade";
import ProjectCards from "@/components/projetos/cards";


function Home() {

    return (
        <>
            <Head>
                <title>Project View</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="flex justify-center">
                    <div className=" absolute  top-64 h-1/4 z-50 w-1/2  items-center justify-center   md:flex  ">
                        <ProjectCards />
                    </div>
                </div>
            </main>
        </>
    );
}

export default Home;